// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package computing

import (
	_ "embed"
	db2 "github.com/swanchain/go-computing-provider/internal/db"
)

// Injectors from wire.go:

func NewTaskService() TaskService {
	db := db2.NewDbService()
	taskService := TaskService{
		DB: db,
	}
	return taskService
}

func NewJobService() JobService {
	db := db2.NewDbService()
	jobService := JobService{
		DB: db,
	}
	return jobService
}
